overlay/ports/libkeyfinder/CONTROL, overlay/ports/libkeyfinder/portfile.cmake, overlay/ports/libkeyfinder/vcpkg.json
Try to fix Mixxx build error:
```
-- Found KeyFinder: D:/a/mixxx/mixxx/build/vcpkg_installed/x64-windows/lib/keyfinder.lib
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPkgConfig.cmake:75 (set):
Syntax error in cmake code at
C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/FindPkgConfig.cmake:75
when parsing string
\a\mixxx\mixxx\build\vcpkg_installed\x64-windows\debug\lib\pkgconfig/../..
Invalid character escape '\a'.
Call Stack (most recent call first):
C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules …
```
=> [libkeyfinder] update to 2.2.4

overlay/osx/protobuf/fix-default-proto-file-path.patch, overlay/osx/protobuf/fix-static-build.patch, overlay/osx/protobuf/port_def.patch, overlay/osx/protobuf/portfile.cmake, overlay/osx/protobuf/protobuf-targets-vcpkg-protoc.cmake, overlay/osx/protobuf/vcpkg-cmake-wrapper.cmake, overlay/osx/protobuf/vcpkg.json
Set visibility to "hidden" to avoid a linker warning
Apple's ld warns
"direct access in function ... to global weak symbol. The weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
=> Fix protobuf warning on MacOS

overlay/osx/qt5-base/CONTROL, overlay/osx/qt5-base/vcpkg-cmake-wrapper.cmake
Qt libraries have _debug suffix. pcre has no suffix for its debug
build.
=> [qt5-base] fix vcpkg-cmake-wrapper to find debug libs on macOS

overlay/osx/qt5-base/vcpkg-cmake-wrapper.cmake
FindSQLite3.cmake included in CMake exports a SQLite::SQLite3
target:
https://cmake.org/cmake/help/latest/module/FindSQLite3.html
=> [qt5-base] fix linking of SQLite in vcpkg-cmake-wrapper.cmake

.github/workflows/build.yml
This set the host triplet to the value of the target triplet to not compile the packages in cross-compile mode. 
This will fix the build failure of https://github.com/mixxxdj/mixxx/pull/4570 a regression from https://github.com/mixxxdj/vcpkg/pull/26
=> Set VCPKG_DEFAULT_HOST_TRIPLET

overlay/osx/qt5-base/patches/QCocoaDrag-avoid-using-the-deprecated-API-if-possibl.patch, overlay/osx/qt5-base/patches/nsimage_qimage.patch, overlay/osx/qt5-base/portfile.cmake, overlay/osx/qt5-base/vcpkg.json
This aims to fix the drag and drop issue reported here: https://github.com/mixxxdj/mixxx/pull/4717
This PR is on top of https://github.com/mixxxdj/vcpkg/pull/45
=> Macos qt drag and drop fix

overlay/osx/qt5-base/vcpkg.json
This aim to fix the build failure after the GitHub workflow runner has updated the system PostgreSQL
The build of the vcpkg environment suffers the same issue as our main branch at https://github.com/mixxxdj/mixxx
```
CMake Error at /usr/local/Cellar/cmake/3.24.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PostgreSQL (missing: PostgreSQL_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/local/Cellar/cmake/3.24.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
/usr/local/Cellar/cmake/3.24.1/share/cmake/Modules/FindPostgreSQL.cmake:269 (find_package_handle_standard_args)
/Users/runner/mixxx-vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
/Users/runner/mixxx-vcpkg/installed/x64-osx-min1012/share/qt5 …
```
=> [qt5-base] Require libpq

overlay/osx/qt5-base/cmake/find_qt_mkspec.cmake, overlay/osx/qt5-base/portfile.cmake
This fixes an issue that prevented users from building Qt for arm64 macOS on arm64 macOS hosts directly, since Qt 5.12's build system apparently defaults to using Rosetta when the host mkspec is left undefined, causing linker errors when building `qt5-tools` (since mixing and matching x86_64 and arm64 libraries of course does not work).
In short: Another step towards making it easy to build Mixxx's dependencies on arm64 macOS hosts.
cc @daschuer, I vaguely recall you having mentioned that you already added such a check, based on `uname -m`. I couldn't find this in the tree, so I suppose it hasn't been merged yet? This patch performs the check by comparing the host triplet prefix to `arm64-osx` instead, which should hopefully be somewhat robust. (Unfortunately, vcpkg doesn't offer a …
=> Set `VCPKG_QT_HOST_MKSPEC` on arm64 macOS hosts explicitly

overlay/triplets/arm64-osx-min1100.cmake, overlay/triplets/arm64-osx.cmake
This is one the last missing pieces to make Apple Silicon (M*) builds possible. These triplets can be used both to compile directly on arm64 macOS machines and to cross-compile from x86_64.
As macOS 11 runners are now supported by GitHub Actions, we also no longer need to hardcode a sysroot/Xcode version, so they should be easy to reuse in different contexts.
The reason why we still have separate `arm64-osx-min1100` and `arm64-osx` triplets is convenience: When building directly on an arm64 macOS machine, the latter is set as the default triplet and lets a user who e.g. only builds for development and doesn't care about running on older macOS versions get started quickly.
=> Add `arm64-osx` triplets

.github/workflows/build.yml
This fixes building on the MacOS 11 workflow runner. 
It seems that it has been broken due to an upstream change. 
https://github.com/daschuer/vcpkg/actions/runs/4069242371
This implements the suggested fix in the error message: 
```
Could not find pkg-config.  Please install it via your package manager:
brew install pkg-config
```
=> Install pkg-config via brew

overlay/osx/qt5-base/cmake/qt_build_submodule.cmake, overlay/osx/qt5-base/vcpkg.json
This effectively applies 7cbfaed7e1b7d3a12aaa2122e4148387f37b1b2e, fixing the cross-compilation of Qt and thereby making it possible to cross-build Mixxx for arm64 macOS again.
@daschuer
=> Backport `vcpkg_configure_qmake` to fix Qt cross-build

.github/workflows/build.yml
This helps to distinguish the release only environment from the release/debug after download.
=> Added -rel suffix to the release only mixxx-deps

overlay/osx/qt5-base/patches/replace_result_of.patch, overlay/osx/qt5-base/portfile.cmake
This is required, to compile the source with clang c++20
=> [qt5-base] Add Patch to replace std::result_of with decltype

overlay/osx/qt5-base/cmake/qt_download_submodule.cmake, overlay/osx/qt5-base/patches/scrollbars_style.patch, overlay/osx/qt5-base/portfile.cmake, overlay/osx/qt5-base/vcpkg.json, scripts/cmake/vcpkg_acquire_msys.cmake, scripts/cmake/vcpkg_configure_make.cmake, scripts/test_ports/vcpkg-ci-msys2/portfile.cmake, scripts/test_ports/vcpkg-ci-msys2/vcpkg.json
This is a backport of a Qt6.2 patch fixing QTBUG-98289
This aims to fix https://github.com/mixxxdj/mixxx/issues/9495
Mixxx builds using this Environment can be found here: 
https://github.com/daschuer/mixxx/actions/runs/5240066209
This also include the minimum changes to keep the vcpkg process working.
=> Scrollbar overlap fix for macOS 

.github/workflows/build.yml
A cherry-pick of the same 2.4 commit.
=> Install Google Benchmark to the 2.5 branch

.github/workflows/build.yml
This aims to fix the following warnig: 
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
=> Replace deprecated ::set-output

overlay/ports/libmad/CMakeLists.txt, overlay/ports/libmad/vcpkg.json
This enables the precision 64 Bit integer math. 
Fixing bug https://github.com/mixxxdj/mixxx/issues/11888
=> [libmad] Detect the FPM flag according to the CMAKE_SYSTEM_PROCESSOR

overlay/osx/qt5-base/patches/qmake_xcode15.patch, overlay/osx/qt5-base/portfile.cmake
This fixes an issue that prevents Qt 5 from building under Xcode 15 (macOS 14 Sonoma), namely:
```
Project ERROR: failed to parse default search paths from compiler output
```
The issue was identified by Homebrew maintainers and fixed by backporting a patch from Qt 6 (which this PR adds):
- https://github.com/Homebrew/homebrew-core/pull/145729
- https://github.com/Homebrew/homebrew-core/issues/144051
- https://bugreports.qt.io/browse/QTBUG-117225
This problem didn't surface in CI yet, since the runners use an older macOS/Xcode version. Still, it would be pretty useful to have this patch so developers can keep building 2.4 environments on their own Macs.
Marked as a draft for now, since there seems to be another error, even after applying this patch, namely:
```
ERROR: Feature …
```
=> [qt5-base] Add patch for Xcode 15

ports/soundtouch/portfile.cmake, ports/soundtouch/vcpkg.json
For some reasons it has changed.
=> [soundtouch] Update changed SHA512 of repacked source code archive

.github/workflows/build.yml
Upstream has renamed this port to `ableton-link` and the old `ableton` port is only kept around for compatibility:
- https://github.com/microsoft/vcpkg/pull/28892
- https://github.com/microsoft/vcpkg/pull/29434
We should probably cherry-pick this to the other branches too (2.4, 2.4-rel, 2.5).
=> Update dependency name to `ableton-link`

.github/workflows/build.yml
=> [2.4] Update dependency name to `ableton-link`

.github/workflows/build.yml
This fixes building after GitHub has updated the macos11 workflow runner. 
2.5 is not affected because Qt 6 no longer depends on fontconfig
=> 2.4 build fix

.github/workflows/build.yml, vcpkg.json
This is a prove of concept PR for the vcpkg manifest mode.
Advantages: 
* Upload of single packages to "GitHub packages"
* Works on the contributors repro. 
* Maintains in place failure notification 
* Optional provides the binary blob, that people can use independent from a GitHub Account.
=> Switch to manifest mode

scripts/cmake/vcpkg_find_acquire_program.cmake
The original version is no longer available.
This should fix the build error in the 2.4-rel branch. 
2.4 is merged into 2.4-rel
=> 2.4: Upade libwinpthread

ports/soundtouch/portfile.cmake, ports/soundtouch/vcpkg.json, versions/baseline.json, versions/s-/soundtouch.json
This is a cherry-pick of microsoft/vcpkg#35269, which updates the checksum of `soundtouch` as per https://github.com/mixxxdj/vcpkg/pull/92#issuecomment-1822987998.
=> [soundtouch] Update SHA512 checksum

overlay/ports/portaudio/0001-Add-basic-support-for-iOS-to-portaudio.patch, overlay/ports/portaudio/0002-Update-CMakeLists-with-iOS-implementation.patch, overlay/ports/portaudio/0003-Fix-renamed-memory-allocation-functions.patch, overlay/ports/portaudio/portfile.cmake, overlay/ports/portaudio/vcpkg.json
This adds https://github.com/PortAudio/portaudio/pull/881 to PortAudio, enabling builds targeting iOS. Once upstreamed, these patches can be removed.
=> [portaudio] Add iOS patches

.github/workflows/build.yml, overlay/triplets/arm64-osx-min1100-release.cmake, overlay/triplets/x64-osx-min1015-release.cmake
As discussed in https://github.com/mixxxdj/vcpkg/pull/111#issuecomment-1928490919, here is a small patch that adds the arm64 macOS cross-build to the regular 2.5 branch for testing. Note that this is only a release build, since debug cross-builds are too time/memory intensive for the GitHub runners.
=> Add arm64 macOS release CI to regular 2.5 branch

vcpkg.json
A minor update to reflect that the manifest represents the dependencies for Mixxx 2.5.
=> Bump manifest version to 2.5.0

vcpkg.json
This modularizes the Qt dependencies into two features `qt5` and `qt6` with `qt6` enabled by default. Thus the default build should work exactly as before, but users can now build with Qt 5 with
```sh
./vcpkg install --x-no-default-features --x-feature qt5 ...
```
=> Add support for building 2.5 environment with Qt 5 via optional `qt5` feature

ports/portmidi/vcpkg.json, versions/baseline.json, versions/p-/portmidi.json
Cherry-pick of https://github.com/microsoft/vcpkg/pull/36613 onto 2.5 so we can progress with #116.
=> [portmidi] Scope alsa dependency to Linux

ports/qtbase/portfile.cmake, ports/qtbase/vcpkg.json
Cherry-pick of https://github.com/microsoft/vcpkg/pull/36407 onto 2.5 as part of the effort to support building for iOS.
=> [qtbase] Add support for OpenGL ES 3.0

overlay/ports/portmidi/ios-support.patch, overlay/ports/portmidi/portfile.cmake, overlay/ports/portmidi/usage, overlay/ports/portmidi/vcpkg.json
This vendors the `portmidi` port until https://github.com/PortMidi/portmidi/pull/65 is merged. Note that this version of PortMidi is based on the latest `master`, which means we can also drop the other two patches.
=> [portmidi] Add overlay with iOS patches

ports/libmodplug/portfile.cmake, ports/libmodplug/vcpkg.json, versions/baseline.json, versions/l-/libmodplug.json
Cherry-pick of https://github.com/microsoft/vcpkg/pull/37090 onto 2.5.
=> [libmodplug] Fix WASM build by pinning C++ standard to 11 (#37090)

ports/soundtouch/portfile.cmake, ports/soundtouch/use-o3-emscripten.patch, ports/soundtouch/vcpkg.json, versions/baseline.json, versions/s-/soundtouch.json
Cherry-pick of https://github.com/microsoft/vcpkg/pull/37103 onto 2.5
=> [soundtouch] Fix WASM build by using -O3 instead of -Ofast (#37103)

ports/libmad/portfile.cmake, ports/libmad/vcpkg.json, versions/baseline.json, versions/l-/libmad.json
Cherry-pick of https://github.com/microsoft/vcpkg/pull/37088 onto 2.5.
=> [libmad] Fix WASM build by disabling asm-based optimizations (#37088)

ports/libflac/portfile.cmake, ports/libflac/vcpkg.json, versions/baseline.json, versions/l-/libflac.json
Cherry-pick of https://github.com/microsoft/vcpkg/pull/37086 onto 2.5.
=> [libflac] Fix WASM build by disabling stack protector via feature

vcpkg.json
From what I understand, these libraries are only skipped on Apple platforms because `SoundSourceCoreAudio` already takes care of this, and are otherwise required for MP3 support.
Therefore `!osx & !ios` should be the correct bound, which would also handle the Emscripten/Wasm case correctly (currently `libid3tag` is only built on Windows, thus MP3 decoding doesn't work on Wasm).
=> Scope `libid3tag` and `libmad` to `!osx & !ios` (to fix Wasm MP3 support)

ports/icu/portfile.cmake, ports/icu/vcpkg-cross-data.patch, ports/icu/vcpkg.json, versions/baseline.json, versions/i-/icu.json
The [latest build errors from the Wasm branch](https://github.com/mixxxdj/vcpkg/actions/runs/8380584291/job/22950128900?pr=140) look suspiciously similar to https://github.com/microsoft/vcpkg/issues/35464, therefore this cherry-picks the ICU patches from
- https://github.com/microsoft/vcpkg/pull/35529
- https://github.com/microsoft/vcpkg/pull/34539 (also included since the other patch is based on this one)
=> [icu] Cherry-pick Wasm fixes to 2.5

.github/workflows/build.yml, overlay/triplets/x64-osx-min1100-release.cmake, overlay/triplets/x64-osx-min1100.cmake
The 2.5 buildenv contains Qt6.5, which has macOS 11 as minimum system requirement: https://doc.qt.io/qt-6.5/supported-platforms.html#desktop-platforms
Therefore I raised the mimimum required macOS version to 11.0.
The x86_64 computer models supported by macOS 11 are very limited, I checked, that each of them has a processor with AVX instruction set. Therefore AVX is set as default for macOS now.
I've no Mac myself and can't verify/measure that the setting does, what it should.
=> Raise minimum macOS version to 11 (Qt6.5 requirement) and use AVX instruction set

ports/libdjinterop/portfile.cmake, ports/libdjinterop/vcpkg.json, versions/baseline.json, versions/l-/libdjinterop.json
Adds version 0.21.0 of libdjinterop.
=> [libdjinterop] Update to 0.21.0 (#38888)

ports/libdjinterop/portfile.cmake, ports/libdjinterop/vcpkg.json, versions/baseline.json, versions/l-/libdjinterop.json
=> Libdjinterop 0.21.0 (2.5)

.github/workflows/build.yml, ports/libdjinterop/portfile.cmake, ports/libdjinterop/vcpkg.json, versions/baseline.json, versions/l-/libdjinterop.json
Cherry picked from https://github.com/microsoft/vcpkg/pull/41251
=> [libdjinterop] Update to 0.22.1 for 2.4

ports/libdjinterop/portfile.cmake, ports/libdjinterop/vcpkg.json, versions/baseline.json, versions/l-/libdjinterop.json
Cherry picked from https://github.com/microsoft/vcpkg/pull/41251
=> [libdjinterop] Update to 0.22.1 for 2.5

.github/workflows/build.yml, .github/workflows/check_issues.yml, .github/workflows/stale.yml, scripts/cmake/vcpkg_acquire_msys.cmake, scripts/cmake/vcpkg_find_acquire_program(PKGCONFIG).cmake, scripts/cmake/vcpkg_find_fortran.cmake, scripts/test_ports/vcpkg-ci-msys2/portfile.cmake
Make branch build again by updating from no longer available msys2 version and workflow runner.
=> 2.5 maintanance

overlay/ports/ffmpeg/portfile.cmake, overlay/ports/ffmpeg/vcpkg.json
AAC is licensed per device. 
We use them already in Mixxx, so there cannot be an issue with using them via FFmpeg as well. 
This allows contributors to easily compare AAC codecs during the 2.6-beta
=> [ffmpeg] Enable codecs which are already licensed by Apple/Microsoft

.github/workflows/build.yml
This adds a new dependency package for home builds on Apple Silicon device. 
To avoid confusion, I have renamed the packages, removed the unimportant "mixx1100" part and added "cross" in case of cross-compile.  
I consider to entirely drop the cross-compile environment in 2.6. but I don't intend to do it in the stable 2.5 branch, to not introduce such a mayor change.
=> Native arm64-osx build on macos-14 runner and Xcode 15.4

.github/workflows/build.yml
- Update build.yml to install rsync via Chocolatey
- Use bash from 'Git or Windows' instead of the MSYS version
=> Replace MSYS tools by native versions to support Windows on ARM64

vcpkg.json
=> BackUp: 7zip & bit7z to vcpkg.json

.github/workflows/build.yml
This is a back-port of the same PR for 2.6 #180 but here for 2.5. 
Also the 2,5 branch has been confirmed working without this here: 
https://github.com/daschuer/vcpkg/actions/runs/15944336081
=> Revert "Install TrustedSigning PowerShell modul"
